// Generated by https://quicktype.io

export interface Character {
    id:           string;
    name:         string;
    japaneseName: string;
    image:        string;
    abilities:    string;
    nationality:  string;
    catchphrase:  string;
    family:       string;
    chapter:      string;
    living:       boolean;
    isHuman:      boolean;
}
